In [99]:
import numpy as np
import matplotlib.pyplot as plt 
!pip install tensorflow

  Using cached protobuf-7.34.1-cp310-abi3-macosx_10_9_universal2.whl.metadata (595 bytes)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 223.5/223.5 MB 4.0 MB/s eta 0:00:00m eta 0:00:010:00:02
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 4.9 MB/s eta 0:00:004.9 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 4.9 MB/s eta 0:00:00 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.8/25.8 MB 4.6 MB/s eta 0:00:000:00:01m eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 676.9/676.9 kB 4.2 MB/s eta 0:00:00
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.25.3
    Uninstalling protobuf-4.25.3:
      Successfully uninstalled protobuf-4.25.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.37.1 requires cachetools<6,>=4.0, but you have cachetools 6.2.6 which is incompatible.
stre

In [83]:
A = np.array([[200],
              [17]])
print(A)

[[200]
 [ 17]]


In [85]:
AT = A.T
print(AT)

[[200  17]]


In [87]:
W = np.array([[1,-3,5],
              [-2,4,-6]])
print(W)
B = np.array([[-1,1,2]])
print(B)

[[ 1 -3  5]
 [-2  4 -6]]
[[-1  1  2]]


In [89]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))
    
def dense(AT , W , B):
    D = AT @ W
    Z = D + B
    A1 = sigmoid(Z)
    return A1 

In [91]:
a_out = dense(AT , W , B)
print(a_out)

[[1.00000000e+000 2.45261912e-231 1.00000000e+000]]


In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense 
import matplotlib.pyplot as plt 